In [1]:
import pandas as pd
df = pd.read_excel('S:\Car\checking.xlsx')
df.shape

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Hp\AppData\Local\Temp\ipykernel_15392\1134053903.py:2: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_excel('S:\Car\checking.xlsx')


(8369, 51)

In [2]:
df['Comfort & Convenience'].value_counts()

Comfort & Convenience
11    637
10    551
16    520
15    519
17    507
14    450
12    446
13    443
20    390
9     389
19    346
21    332
18    305
23    292
8     229
5     220
22    212
7     196
24    194
27    170
6     167
25    150
29    128
26    122
28     96
0      68
31     59
30     59
2      43
32     37
33     21
3      20
4      18
1      14
34      9
35      7
37      3
Name: count, dtype: int64

In [229]:
df.columns

Index(['Unnamed: 0', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'variantName', 'Insurance Validity', 'Fuel Type',
       'Engine Displacement', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Entertainment & Communication', 'Max Power', 'Torque', 'Wheel Size',
       'Seats_y', 'Color', 'Engine Type', 'No of Cylinder',
       'Values per Cylinder', 'Fuel Suppy System', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'No Door Numbers', 'Mileage', 'Value Configuration',
       'Compression Ratio', 'Super Charger', 'Front Tread', 'Rear Tread',
       'Gross Weight', 'Turning Radius', 'Top Speed', 'Acceleration',
       'BoreX Stroke', 'City', 'price_in_lakhs', 'Registration Year New',
       'Gear'],
      dtype='object')

In [16]:
df['Wheel Size'] = df['Wheel Size'].astype(str)
df['Wheel Size'] = df['Wheel Size'].replace(',','',regex=True).replace('m','',regex=True).replace('mm','',regex=True).replace('R','',regex=True)
df['Wheel Size'].value_counts()

Wheel Size
2450     662
2600     454
2425     430
2520     403
2380     380
        ... 
2855       1
2795       1
2825       1
2480       1
2622       1
Name: count, Length: 218, dtype: int64

In [17]:
df['Height'] = df['Height'].astype(str)
df['Width'] = df['Width'].astype(str)
df['Length'] = df['Length'].astype(str)
df['Height'] = df['Height'].replace(',','',regex=True)
df['Width'] = df['Width'].replace(',','',regex=True)
df['Length'] = df['Length'].replace(',','',regex=True)

In [18]:
df.drop(columns=['Gear Box'],axis=1,inplace=True)

In [19]:
import re
def clean(x):
    pattern = r'^(\d{4})-'
    re.match(pattern, x)


In [20]:
df.drop(columns=['Height','Width','Length'],axis=1,inplace=True)

In [21]:
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())

In [22]:
df['Gear'] = df['Gear'].fillna(df['Gear'].mode()[0])

In [23]:
df.dtypes

Unnamed: 0                         int64
km                                 int64
transmission                       int64
ownerNo                            int64
oem                                int64
model                              int64
modelYear                          int64
variantName                        int64
Insurance Validity                 int64
Fuel Type                          int64
Engine Displacement                int64
Year of Manufacture                int64
Features                           int64
Comfort & Convenience              int64
Interior                           int64
Exterior                           int64
Safety                             int64
Entertainment & Communication      int64
Max Power                          int64
Torque                             int64
Wheel Size                        object
Seats_y                            int64
Color                              int64
Engine Type                        int64
No of Cylinder  

In [24]:
df.drop(['Wheel Size'],axis=1,inplace=True)

In [25]:
#outliers 
from scipy import stats
import numpy as np
# Assuming df is your DataFrame
# Calculate the Z-scores
z_scores = stats.zscore(df)

# Remove outliers (keeping only those with Z-score < 3 in absolute value)
df = df[(np.abs(z_scores) < 3).all(axis=1)]


In [26]:
corr_df = df.corr()
corr_df

Unnamed: 0        km  transmission   ownerNo  \
Unnamed: 0                       1.000000  0.007951     -0.020021  0.005120   
km                               0.007951  1.000000      0.129315  0.237530   
transmission                    -0.020021  0.129315      1.000000  0.024170   
ownerNo                          0.005120  0.237530      0.024170  1.000000   
oem                              0.010873 -0.000693      0.047374 -0.033808   
model                            0.012878  0.013334      0.035435 -0.023799   
modelYear                       -0.048961 -0.544237     -0.162670 -0.336874   
variantName                     -0.003573 -0.091831      0.098436 -0.060937   
Insurance Validity               0.049869  0.106330      0.082455  0.090224   
Fuel Type                       -0.003977 -0.338401      0.053863 -0.035343   
Engine Displacement              0.011254 -0.087360     -0.103784 -0.014424   
Year of Manufacture             -0.048961 -0.544237     -0.162670 -0.336874   
Features                        -0.035098 -0.070254     -0.176821 -0.073126   
Comfort & Convenience           -0.038941 -0.108486     -0.406664 -0.107393   
Interior                        -0.043516 -0.061229     -0.373625 -0.077912   
Exterior                        -0.046420 -0.190089     -0.368795 -0.125565   
Safety                          -0.054063 -0.243432     -0.387734 -0.189905   
Entertainment & Communication   -0.057241 -0.272048     -0.302014 -0.186366   
Max Power                        0.010808  0.022671      0.208525  0.022118   
Torque                          -0.006606  0.023410     -0.113662  0.002372   
Seats_y                          0.005963  0.089535     -0.006356  0.000756   
Color                            0.003512  0.063614      0.034735  0.041046   
Engine Type                      0.014031  0.125915      0.018307  0.060003   
No of Cylinder                  -0.017505  0.133033     -0.094996  0.008654   
Values per Cylinder             -0.028030 -0.076468     -0.074555 -0.048988   
Fuel Suppy System               -0.009648 -0.205908      0.018545 -0.015576   
Turbo Charger                    0.012803  0.128616     -0.131218 -0.046709   
Drive Type                       0.025103 -0.003450      0.045859  0.022114   
Seating Capacity                 0.005963  0.089535     -0.006356  0.000756   
Steering Type                   -0.016939  0.256769      0.018712  0.119702   
No Door Numbers                 -0.009379 -0.103241      0.084370 -0.040880   
Mileage                          0.015120  0.023729      0.218750 -0.034227   
Value Configuration              0.027611 -0.018988      0.061042  0.032235   
Compression Ratio                0.087130  0.074816      0.037511  0.038967   
Super Charger                   -0.005490  0.295741      0.040102  0.168428   
Front Tread                     -0.027372  0.012493     -0.198528 -0.026384   
Rear Tread                      -0.025494  0.011738     -0.193749 -0.025546   
Gross Weight                    -0.033516  0.070281     -0.109211  0.018542   
Turning Radius                  -0.044048 -0.079631     -0.204212 -0.069649   
Top Speed                       -0.048461 -0.025465     -0.209280 -0.036049   
Acceleration                     0.003565 -0.021445     -0.136599 -0.017758   
BoreX Stroke                     0.036244 -0.001861     -0.064196  0.027026   
City                            -0.071991 -0.027630      0.092282 -0.069344   
price_in_lakhs                  -0.052598 -0.211973     -0.454827 -0.138118   
Registration Year New           -0.049769 -0.341419     -0.102611 -0.153242   
Gear                            -0.024866 -0.032158     -0.351930 -0.042301   

                                    oem     model  modelYear  variantName  \
Unnamed: 0                     0.010873  0.012878  -0.048961    -0.003573   
km                            -0.000693  0.013334  -0.544237    -0.091831   
transmission                   0.047374  0.035435  -0.162670     0.098436   
ownerNo  

In [27]:
correlation_with_price = corr_df['price_in_lakhs'].sort_values(ascending=False)
correlation_with_price

price_in_lakhs                   1.000000
Comfort & Convenience            0.590505
Safety                           0.565416
Exterior                         0.536553
Interior                         0.499653
Gear                             0.485819
Entertainment & Communication    0.449537
Year of Manufacture              0.361656
modelYear                        0.361656
Turning Radius                   0.344630
Front Tread                      0.286218
Rear Tread                       0.277578
Turbo Charger                    0.276940
Top Speed                        0.261356
Registration Year New            0.231852
Gross Weight                     0.208778
Features                         0.193109
Acceleration                     0.177042
No of Cylinder                   0.171533
Seats_y                          0.153502
Seating Capacity                 0.153502
Torque                           0.148714
Engine Displacement              0.114970
Values per Cylinder              0

In [30]:
relevant_features = correlation_with_price[correlation_with_price>0.35].index
relevant_features_2 = correlation_with_price[correlation_with_price<-0.35].index
relevant_features_2

Index(['transmission'], dtype='object')

In [31]:
final_features = relevant_features.append(relevant_features_2)
final_features

Index(['price_in_lakhs', 'Comfort & Convenience', 'Safety', 'Exterior',
       'Interior', 'Gear', 'Entertainment & Communication',
       'Year of Manufacture', 'modelYear', 'transmission'],
      dtype='object')

In [246]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [270]:
len(relevant_features)

15

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

df[final_features] = sc.fit_transform(df[final_features])

In [214]:
df

km  transmission  ownerNo  oem  model  modelYear  variantName  \
0     32706             1        3   20    160      -0.52         1806   
1     32706             1        2    6     50       0.36          288   
2     11949             1        1   29    273       0.36          129   
3     17794             1        1    9     87      -0.81          101   
4     60000             1        1   20    178      -0.52          987   
...     ...           ...      ...  ...    ...        ...          ...   
8357  30000             1        1    9     74      -1.39         1352   
8358  50000             1        1   20    184      -0.52         1823   
8361  60000             1        1    8     63      -1.10         1754   
8362  70000             1        1   31    300      -0.52          113   
8363  30000             1        1    9     82      -2.27         1135   

      Insurance Validity  Fuel Type  Engine Displacement  ...  Rear Tread  \
0                      5          4                  148  ...          32   
1                      2          4                   44  ...          33   
2                      2          4                   14  ...          33   
3                      2          4                   12  ...          63   
4                      5          1                   15  ...          39   
...                  ...        ...                  ...  ...         ...   
8357                   5          4                  143  ...          25   
8358                   5          4                  148  ...          13   
8361                   5          4                   44  ...          44   
8362                   5          4                   14  ...          44   
8363                   5          4                    3  ...          15   

      Gross Weight  Turning Radius  Top Speed  Acceleration  BoreX Stroke  \
0               13           -1.01         40           135            29   
1              108            0.14         41           122            99   
2              112           -0.72         41           122            77   
3              112           -1.01        125           119            15   
4              112           -0.12        163            55            15   
...            ...             ...        ...           ...           ...   
8357            28           -1.14         16           177            11   
8358            28           -1.14         50           175            11   
8361            59            0.12        105           119            54   
8362            59           -0.67        105           119            54   
8363            15           -1.32         24           149             6   

      City  price_in_lakhs  Registration Year New  Gear  
0        0           -0.50                     16 -0.50  
1        0           -0.03                     16 -0.50  
2        0           -0.29                     16 -0.50  
3        0           -0.43                     12 -0.50  
4        0           -0.05                     15 -0.50  
...    ...             ...                    ...   ...  
8357     5           -0.72                     22 -0.50  
8358     5           -0.62                     22 -0.50  
8361     5           -0.50                     22 -0.50  
8362     5           -0.54                     22 -0.50  
8363     5           -0.78                     22 -0.50  

[7357 rows x 45 columns]

In [248]:
df.isna().sum()

km                               0
transmission                     0
ownerNo                          0
oem                              0
model                            0
modelYear                        0
variantName                      0
Insurance Validity               0
Fuel Type                        0
Engine Displacement              0
Year of Manufacture              0
Features                         0
Comfort & Convenience            0
Interior                         0
Exterior                         0
Safety                           0
Entertainment & Communication    0
Max Power                        0
Torque                           0
Seats_y                          0
Color                            0
Engine Type                      0
No of Cylinder                   0
Values per Cylinder              0
Fuel Suppy System                0
Turbo Charger                    0
Drive Type                       0
Seating Capacity                 0
Steering Type       

In [34]:
X = df[final_features]
X.drop('price_in_lakhs',axis=1,inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_20604\4161199439.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('price_in_lakhs',axis=1,inplace=True)


In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, df['price_in_lakhs'], test_size=0.3, random_state=0)


In [36]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()


In [37]:
model.fit(X_train,y_train)

RandomForestRegressor()

In [38]:
y_pred = model.predict(X_test)
y_pred

array([-0.12070487, -0.16111524, -0.58185257, ...,  0.41666365,
        0.20211929, -0.61474981])

In [39]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8279386227784832

In [40]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_pred)

np.float64(0.1549667307655529)

In [95]:
import lazypredict

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, df['price_in_lakhs'], test_size=0.3, random_state=0)

In [42]:
from sklearn.svm import SVR

svr = SVR()

svr.fit(X_train,y_train)

y_pred = svr.predict(X_test)
y_pred


array([-0.15949699, -0.21226009, -0.66006606, ..., -0.00261219,
        0.32799433, -0.56141308])

In [43]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7085939222094879

In [44]:
from xgboost import XGBRegressor

In [45]:
xgbr = XGBRegressor()
xgbr.fit(X_train,y_train)

y_pred = xgbr.predict(X_test)
y_pred

array([-0.07271981, -0.10745092, -0.53762794, ...,  0.21396244,
        0.19041005, -0.5218403 ], dtype=float32)

In [46]:
r2_score(y_test, y_pred)

0.8316575399149115

In [225]:
len(relevant_features)

10

In [47]:
import pickle
with open("random_forest_model.pkl", "wb") as f:
    pickle.dump(model, f)


In [48]:
import pickle
with open("XGB_model.pkl", "wb") as f:
    pickle.dump(xgbr, f)

In [260]:
y_pred

array([ 6.608196 ,  5.7443094,  3.7511892, ..., 13.615687 ,  2.9886835,
        7.721748 ], dtype=float32)

In [49]:
final_features

Index(['price_in_lakhs', 'Comfort & Convenience', 'Safety', 'Exterior',
       'Interior', 'Gear', 'Entertainment & Communication',
       'Year of Manufacture', 'modelYear', 'transmission'],
      dtype='object')

In [50]:
df['transmission'].value_counts()

transmission
 0.591375    5450
-1.690974    1906
Name: count, dtype: int64

In [ ]:
raw_df = pd.read